version: '3.8'  # Specify the version of Docker Compose

services:

  db:
    image: postgres:13  # Use the official PostgreSQL image
    restart: always  # Restart the container if it stops
    environment:
      - POSTGRES_DB=german_placement_test  # Name of the database to create
      - POSTGRES_USER=german  # Database user
      - POSTGRES_PASSWORD=german  # Database password
    ports:
      - "5432:5432"  # Map port 5432 of the container to port 5432 on the host
    networks:
      - app-network  # Connect to the same network as the app

networks:
  app-network:  # Define a custom network