INSERT INTO question (question_text, level, options, correct_option) VALUES
('What is the German word for "house"?', 'A1', '["Haus", "Baum", "Stuhl", "Auto"]', 'Haus'),
('How do you say "thank you" in German?', 'A1', '["Danke", "Bitte", "Hallo", "Tschüss"]', 'Danke'),
('What is the plural form of "Apfel"?', 'A1', '["Äpfel", "Apfels", "Apfeln", "Apfeles"]', 'Äpfel'),
('Choose the correct form of "sein" for "Ich ___ müde."', 'A1', '["bin", "bist", "ist", "sind"]', 'bin'),
('Translate "good morning" to German.', 'A1', '["Guten Morgen", "Guten Abend", "Guten Tag", "Gute Nacht"]', 'Guten Morgen'),
('What is the correct article for "Auto"?', 'A1', '["der", "die", "das", "den"]', 'das'),
('What is "cat" in German?', 'A1', '["Katze", "Hund", "Maus", "Fisch"]', 'Katze'),
('How do you say "yes" in German?', 'A1', '["Ja", "Nein", "Vielleicht", "Tschüss"]', 'Ja'),
('What is "bread" in German?', 'A1', '["Brot", "Wasser", "Milch", "Käse"]', 'Brot'),
('How do you say "I am a student" in German?', 'A1', '["Ich bin ein Student", "Ich Student bin", "Bin ich Student", "Ich bin Studentin"]', 'Ich bin ein Student'),
('Choose the correct form of "haben" for "Du ___ ein Buch."', 'A1', '["hast", "hat", "haben", "habt"]', 'hast'),
('What is "book" in German?', 'A1', '["Buch", "Kuchen", "Schule", "Lampe"]', 'Buch'),
('How do you ask "Where is the bathroom?" in German?', 'A1', '["Wo ist die Toilette?", "Wo sind die Bücher?", "Wo ist das Essen?", "Wo ist der Hund?"]', 'Wo ist die Toilette?'),
('What is the German word for "dog"?', 'A1', '["Hund", "Katze", "Vogel", "Pferd"]', 'Hund'),
('Translate "I am hungry" to German.', 'A1', '["Ich habe Hunger", "Ich bin durstig", "Ich esse Hunger", "Ich habe Essen"]', 'Ich habe Hunger'),
('Choose the correct pronoun for "Er ___ ein Lehrer."', 'A1', '["ist", "bist", "sind", "seid"]', 'ist'),
('How do you say "please" in German?', 'A1', '["Bitte", "Danke", "Ja", "Nein"]', 'Bitte'),
('Translate "water" to German.', 'A1', '["Wasser", "Milch", "Saft", "Bier"]', 'Wasser'),
('What is the German word for "school"?', 'A1', '["Schule", "Haus", "Auto", "Arzt"]', 'Schule'),
('Choose the correct form of "sprechen" for "Wir ___ Deutsch."', 'A1', '["sprechen", "spricht", "sprichst", "spricht"]', 'sprechen'),
('What is "apple" in German?', 'A1', '["Apfel", "Banane", "Birne", "Kirsche"]', 'Apfel'),
('Translate "thank you very much" to German.', 'A1', '["Vielen Dank", "Bitte sehr", "Guten Tag", "Hallo"]', 'Vielen Dank'),
('How do you say "My name is..." in German?', 'A1', '["Mein Name ist...", "Ich heiße...", "Ich bin...", "Ich werde..."]', 'Mein Name ist...'),
('What is the German word for "tree"?', 'A1', '["Baum", "Busch", "Pflanze", "Blume"]', 'Baum'),
('Translate "I like to read books" to German.', 'A1', '["Ich lese gern Bücher", "Ich mag lesen", "Ich gern lese Bücher", "Lesen ich Bücher gern"]', 'Ich lese gern Bücher');


INSERT INTO question (question_text, level, options, correct_option) VALUES
('Wie sagt man auf Deutsch "Hallo"?', 'A1', '["Hallo", "Tschüss", "Bitte", "Danke"]', 'Hallo'),
('Was ist die korrekte Antwort auf "Wie geht es dir?"', 'A1', '["Gut, danke!", "Ich bin müde", "Es regnet", "Ich spreche kein Deutsch"]', 'Gut, danke!'),
('Wählen Sie das richtige Verb für den Satz: "Ich ___ ein Buch."', 'A1', '["lese", "esse", "trinke", "höre"]', 'lese'),
('Wie sagt man "Thank you" auf Deutsch?', 'A1', '["Danke", "Bitte", "Entschuldigung", "Hallo"]', 'Danke'),
('Welches Wort beschreibt eine Zahl: 5, 10, 15?', 'A1', '["Nummer", "Stuhl", "Buch", "Blume"]', 'Nummer'),
('Welches ist ein Wochentag?', 'A1', '["Montag", "Februar", "Oktober", "Sommer"]', 'Montag'),
('Wählen Sie die richtige Übersetzung für "bread".', 'A1', '["Brot", "Milch", "Wasser", "Apfel"]', 'Brot'),
('Wie sagt man auf Deutsch "Goodbye"?', 'A1', '["Auf Wiedersehen", "Hallo", "Bitte", "Danke"]', 'Auf Wiedersehen'),
('Wählen Sie das richtige Personalpronomen: "___ bin glücklich."', 'A1', '["Ich", "Du", "Er", "Sie"]', 'Ich'),
('Welche Farbe beschreibt "Rot"?', 'A1', '["Red", "Blue", "Green", "Yellow"]', 'Red');


INSERT INTO question (question_text, level, options, correct_option) VALUES
('What is the past tense of "gehen"?', 'A2', '["ging", "gegangen", "geht", "gehen"]', 'ging'),
('Which article is correct for "Auto"?', 'A2', '["der", "die", "das", "den"]', 'das'),
('How do you say "I have a book" in German?', 'A2', '["Ich habe ein Buch", "Ich bin ein Buch", "Ich lese ein Buch", "Ich hat ein Buch"]', 'Ich habe ein Buch'),
('Translate "Can you help me?" to German.', 'A2', '["Kannst du mir helfen?", "Hilfen mir?", "Helfe du mich?", "Du helfen?"]', 'Kannst du mir helfen?'),
('What is the correct form of "müssen" for "Sie ___ gehen"?', 'A2', '["muss", "müssen", "mussst", "musst"]', 'müssen'),
('How do you say "I would like a coffee" in German?', 'A2', '["Ich möchte einen Kaffee", "Ich will ein Kaffee", "Ich mag Kaffee", "Ich liebe Kaffee"]', 'Ich möchte einen Kaffee'),
('Choose the correct form of "essen" for "Er ___ einen Apfel."', 'A2', '["isst", "essen", "esse", "esst"]', 'isst'),
('Translate "I have to study" to German.', 'A2', '["Ich muss lernen", "Ich habe zu lernen", "Ich will lernen", "Ich muss lernen zu"]', 'Ich muss lernen'),
('What is the German word for "train station"?', 'A2', '["Bahnhof", "Flughafen", "Markt", "Hotel"]', 'Bahnhof'),
('How do you say "What time is it?" in German?', 'A2', '["Wie spät ist es?", "Was Uhr ist?", "Wann ist es?", "Wie viele Uhr?"]', 'Wie spät ist es?'),
('Translate "I am going to the supermarket." to German.', 'A2', '["Ich gehe zum Supermarkt", "Ich fahre nach Supermarkt", "Ich bin zum Supermarkt", "Ich gehe in Supermarkt"]', 'Ich gehe zum Supermarkt'),
('What is the past tense of "haben"?', 'A2', '["hatte", "haben", "habe", "hat"]', 'hatte'),
('Choose the correct pronoun for "Der Mann, ___ ich kenne, ist Lehrer."', 'A2', '["den", "die", "das", "der"]', 'den'),
('How do you say "yesterday" in German?', 'A2', '["gestern", "heute", "morgen", "nachmittag"]', 'gestern'),
('Translate "I don’t understand" to German.', 'A2', '["Ich verstehe nicht", "Ich weiß nicht", "Ich sehe nicht", "Ich höre nicht"]', 'Ich verstehe nicht'),
('What is "city" in German?', 'A2', '["Stadt", "Land", "Haus", "Ort"]', 'Stadt'),
('Choose the correct article for "Zeitung".', 'A2', '["die", "der", "das", "den"]', 'die'),
('Translate "The weather is nice today." to German.', 'A2', '["Das Wetter ist schön heute", "Das Wetter ist heute gut", "Es ist gutes Wetter heute", "Es ist schön heute"]', 'Das Wetter ist schön heute'),
('How do you ask "Can I pay with a card?" in German?', 'A2', '["Kann ich mit Karte zahlen?", "Zahlen ich mit Karte?", "Karte zahlen ich?", "Kann zahlen mit Karte?"]', 'Kann ich mit Karte zahlen?'),
('What is "doctor" in German?', 'A2', '["Arzt", "Lehrer", "Student", "Bäcker"]', 'Arzt'),
('Translate "I don’t have money." to German.', 'A2', '["Ich habe kein Geld", "Ich habe Geld nicht", "Kein Geld habe ich", "Ich habe keine Euro"]', 'Ich habe kein Geld'),
('How do you say "I will be late" in German?', 'A2', '["Ich werde spät sein", "Ich spät komme", "Ich werde zu spät", "Ich komme spät an"]', 'Ich werde spät sein'),
('What is the plural form of "Kind"?', 'A2', '["Kinder", "Kinds", "Kindes", "Kindern"]', 'Kinder'),
('Translate "I am looking for a job." to German.', 'A2', '["Ich suche eine Arbeit", "Ich finden eine Arbeit", "Ich bin Arbeit suchen", "Ich suche Job"]', 'Ich suche eine Arbeit'),
('Choose the correct form of "dürfen" for "Ihr ___ hier nicht rauchen."', 'A2', '["dürft", "dürfen", "darf", "dürfte"]', 'dürft'),
('How do you say "I like to travel" in German?', 'A2', '["Ich reise gern", "Ich mag reisen", "Ich bin gern reisen", "Ich mag reise"]', 'Ich reise gern'),
('Translate "What’s your name?" to German.', 'A2', '["Wie heißt du?", "Was ist dein Name?", "Wie heißen du?", "Wer bist du?"]', 'Wie heißt du?'),
('What is "student" in German?', 'A2', '["Student", "Schüler", "Lehrer", "Doktor"]', 'Student'),
('How do you say "My car is broken." in German?', 'A2', '["Mein Auto ist kaputt", "Mein Wagen ist kaputt", "Ich habe kein Auto", "Das Auto geht nicht"]', 'Mein Auto ist kaputt');
INSERT INTO question (question_text, level, options, correct_option) VALUES
('Wie nennt man den Ort, an dem man Lebensmittel kauft?', 'A2', '["Supermarkt", "Schule", "Krankenhaus", "Büro"]', 'Supermarkt'),
('Welches Verb passt? "Er ___ jeden Tag zur Arbeit."', 'A2', '["geht", "isst", "schläft", "lernt"]', 'geht'),
('Was ist die korrekte Übersetzung von "window"?', 'A2', '["Fenster", "Tür", "Bett", "Buch"]', 'Fenster'),
('Wählen Sie die richtige Präposition: "Ich komme ___ Deutschland."', 'A2', '["aus", "bei", "nach", "zu"]', 'aus'),
('Welches Adjektiv beschreibt das Gegenteil von "klein"?', 'A2', '["groß", "dünn", "lang", "schmal"]', 'groß'),
('Wie sagt man "restaurant" auf Deutsch?', 'A2', '["Restaurant", "Küche", "Hotel", "Schule"]', 'Restaurant'),
('Was ist die korrekte Übersetzung von "I need help"?', 'A2', '["Ich brauche Hilfe", "Ich habe Hunger", "Ich gehe arbeiten", "Ich bin müde"]', 'Ich brauche Hilfe'),
('Wählen Sie die richtige Konjugation: "Wir ___ am Wochenende wandern."', 'A2', '["gehen", "gehe", "geht", "ging"]', 'gehen'),
('Welche Jahreszeit ist kalt?', 'A2', '["Winter", "Sommer", "Frühling", "Herbst"]', 'Winter'),
('Wie sagt man "breakfast" auf Deutsch?', 'A2', '["Frühstück", "Mittagessen", "Abendessen", "Snack"]', 'Frühstück');

INSERT INTO question (question_text, level, options, correct_option) VALUES
('Translate "I have already eaten." to German.', 'B1', '["Ich habe schon gegessen", "Ich esse schon", "Ich aß schon", "Ich habe gegessen schon"]', 'Ich habe schon gegessen'),
('What is the correct form of "lesen" for "Wir ___ ein Buch"?', 'B1', '["lesen", "liest", "lest", "lese"]', 'lesen'),
('Choose the correct form for "Ich ___ in Berlin für drei Jahre."', 'B1', '["lebte", "leben", "lebt", "gelebt"]', 'lebte'),
('How do you say "environment" in German?', 'B1', '["Umwelt", "Welt", "Land", "Gesellschaft"]', 'Umwelt'),
('Translate "She works as a teacher." to German.', 'B1', '["Sie arbeitet als Lehrerin", "Sie ist eine Lehrer", "Arbeiten sie als Lehrerin", "Sie arbeitet ein Lehrer"]', 'Sie arbeitet als Lehrerin'),
('What is "to understand" in German?', 'B1', '["verstehen", "hören", "sehen", "wissen"]', 'verstehen'),
('Choose the correct article for "Haus".', 'B1', '["das", "der", "die", "den"]', 'das'),
('Translate "The book is on the table." to German.', 'B1', '["Das Buch liegt auf dem Tisch", "Das Buch ist am Tisch", "Das Buch ist unter Tisch", "Das Buch steht im Tisch"]', 'Das Buch liegt auf dem Tisch'),
('How do you say "to forget" in German?', 'B1', '["vergessen", "verlieren", "finden", "lernen"]', 'vergessen'),
('What is the plural form of "Freund"?', 'B1', '["Freunde", "Freundin", "Freundes", "Freunden"]', 'Freunde'),
('Translate "I will arrive tomorrow." to German.', 'B1', '["Ich werde morgen ankommen", "Ich bin morgen hier", "Ich komme an morgen", "Ich reise morgen an"]', 'Ich werde morgen ankommen'),
('What is the German word for "health"?', 'B1', '["Gesundheit", "Krankheit", "Körper", "Leben"]', 'Gesundheit'),
('Choose the correct form of "fahren" for "Wir ___ nach München."', 'B1', '["fahren", "fährt", "fuhr", "fahrt"]', 'fahren'),
('How do you say "to improve" in German?', 'B1', '["verbessern", "verändern", "vermischen", "vergrößern"]', 'verbessern'),
('Translate "The weather is bad today." to German.', 'B1', '["Das Wetter ist heute schlecht", "Das Wetter heute ist kalt", "Heute ist schlechtes Wetter", "Es ist schlechtes Wetter"]', 'Das Wetter ist heute schlecht'),
('What is "teacher" in German?', 'B1', '["Lehrer", "Schüler", "Dozent", "Arzt"]', 'Lehrer'),
('Choose the correct translation for "I need help."', 'B1', '["Ich brauche Hilfe", "Ich suche Hilfe", "Ich möchte Hilfe", "Ich helfe dir"]', 'Ich brauche Hilfe'),
('How do you say "vacation" in German?', 'B1', '["Urlaub", "Reise", "Pause", "Ferien"]', 'Urlaub'),
('Translate "We are friends." to German.', 'B1', '["Wir sind Freunde", "Wir haben Freunde", "Wir Freunde sind", "Freunde wir sind"]', 'Wir sind Freunde'),
('What is the past tense of "kommen"?', 'B1', '["kam", "kommen", "kamm", "kommt"]', 'kam'),
('Translate "Can you speak slower?" to German.', 'B1', '["Können Sie langsamer sprechen?", "Können Sie schneller sprechen?", "Kannst du leise sprechen?", "Sprechen Sie laut?"]', 'Können Sie langsamer sprechen?'),
('How do you say "dangerous" in German?', 'B1', '["gefährlich", "sicher", "langsam", "vorsichtig"]', 'gefährlich'),
('Choose the correct form of "laufen" for "Er ___ schnell."', 'B1', '["läuft", "laufen", "lief", "laufen"]', 'läuft'),
('Translate "The house is big." to German.', 'B1', '["Das Haus ist groß", "Das Haus hat groß", "Ein großes Haus", "Haus ist groß"]', 'Das Haus ist groß'),
('How do you say "I don’t agree." in German?', 'B1', '["Ich stimme nicht zu", "Ich mag das nicht", "Ich bin zufrieden", "Ich stimme"]', 'Ich stimme nicht zu');
INSERT INTO question (question_text, level, options, correct_option) VALUES
('Welche deutsche Stadt ist bekannt für den Dom?', 'B1', '["Köln", "Berlin", "Hamburg", "München"]', 'Köln'),
('Was ist die korrekte Form? "Ich habe ___ gestern getroffen."', 'B1', '["ihn", "ihm", "er", "sein"]', 'ihn'),
('Was bedeutet "Beruf" auf Englisch?', 'B1', '["Profession", "Hobby", "Haus", "Freizeit"]', 'Profession'),
('Wählen Sie die richtige Konjunktion: "Ich esse, ___ ich Hunger habe."', 'B1', '["weil", "oder", "aber", "wenn"]', 'weil'),
('Wie sagt man "important" auf Deutsch?', 'B1', '["wichtig", "klein", "stark", "schwach"]', 'wichtig'),
('Welches Wort passt? "Die ___ ist heute besonders blau."', 'B1', '["Himmel", "Wasser", "Luft", "Boden"]', 'Himmel'),
('Was ist das Gegenteil von "heiß"?', 'B1', '["kalt", "schnell", "langsam", "hart"]', 'kalt'),
('Wählen Sie die richtige Zeitform: "Als Kind ___ ich oft Fußball."', 'B1', '["spielte", "spiele", "spielen", "gespielt"]', 'spielte'),
('Wie nennt man jemanden, der Bücher schreibt?', 'B1', '["Autor", "Lehrer", "Arzt", "Koch"]', 'Autor'),
('Was bedeutet "zufrieden" auf Englisch?', 'B1', '["satisfied", "angry", "sad", "tired"]', 'satisfied');


INSERT INTO question (question_text, level, options, correct_option) VALUES
('Translate "I need more information about this topic." to German.', 'B2', '["Ich brauche mehr Informationen zu diesem Thema", "Ich benötige Information über Thema", "Mehr Informationen möchte ich haben", "Das Thema braucht Information"]', 'Ich brauche mehr Informationen zu diesem Thema'),
('How do you say "to recommend" in German?', 'B2', '["empfehlen", "vergleichen", "erinnern", "beherrschen"]', 'empfehlen'),
('What is the correct form for "Du ___ das Projekt abschließen."', 'B2', '["musst", "müssen", "möchte", "soll"]', 'musst'),
('Translate "The conference was successful." to German.', 'B2', '["Die Konferenz war erfolgreich", "Das Meeting war gut", "Erfolg für die Konferenz", "Es gab eine gute Konferenz"]', 'Die Konferenz war erfolgreich'),
('Choose the correct synonym for "intelligent" in German.', 'B2', '["klug", "langsam", "traurig", "alt"]', 'klug'),
('What is "responsibility" in German?', 'B2', '["Verantwortung", "Arbeit", "Pflicht", "Freude"]', 'Verantwortung'),
('How do you say "to negotiate" in German?', 'B2', '["verhandeln", "verkaufen", "besprechen", "kaufen"]', 'verhandeln'),
('Translate "The results are promising." to German.', 'B2', '["Die Ergebnisse sind vielversprechend", "Ergebnisse waren schlecht", "Wir haben Ergebnisse", "Ergebnis ist offen"]', 'Die Ergebnisse sind vielversprechend'),
('Choose the correct translation for "satisfaction."', 'B2', '["Zufriedenheit", "Glück", "Hilfe", "Probleme"]', 'Zufriedenheit'),
('Translate "The company is expanding." to German.', 'B2', '["Das Unternehmen erweitert sich", "Die Firma schließt", "Die Firma verkleinert sich", "Das Büro ist neu"]', 'Das Unternehmen erweitert sich'),
('What is "challenge" in German?', 'B2', '["Herausforderung", "Problem", "Glück", "Feier"]', 'Herausforderung'),
('How do you say "to achieve" in German?', 'B2', '["erreichen", "verlieren", "rennen", "schaffen"]', 'erreichen'),
('Translate "He is an experienced manager." to German.', 'B2', '["Er ist ein erfahrener Manager", "Er ist Manager", "Er hat ein Manager", "Er managt Erfahrung"]', 'Er ist ein erfahrener Manager'),
('Choose the correct form for "Ich ___ diese Regel verstehen."', 'B2', '["möchte", "mögen", "magst", "muss"]', 'möchte'),
('Translate "There are many opportunities." to German.', 'B2', '["Es gibt viele Möglichkeiten", "Es sind wenig Chancen", "Es haben Optionen", "Viel gibt hier"]', 'Es gibt viele Möglichkeiten'),
('How do you say "detailed" in German?', 'B2', '["detailliert", "groß", "schnell", "komplett"]', 'detailliert'),
('What is the past tense of "sehen"?', 'B2', '["sah", "gesehen", "sehen", "sehte"]', 'sah'),
('Translate "She is working on the project." to German.', 'B2', '["Sie arbeitet am Projekt", "Sie hat Projekt", "Das Projekt arbeitet", "Sie ist beim Projekt"]', 'Sie arbeitet am Projekt'),
('Choose the correct form of "sprechen" for "Wir ___ oft über das Thema."', 'B2', '["sprechen", "sprach", "spreche", "sprachen"]', 'sprechen'),
('What is "communication" in German?', 'B2', '["Kommunikation", "Verhandlung", "Reden", "Hören"]', 'Kommunikation'),
('Translate "The situation has improved." to German.', 'B2', '["Die Lage hat sich verbessert", "Es ist schlecht", "Lage war gut", "Verbesserung ist"]', 'Die Lage hat sich verbessert');


INSERT INTO question (question_text, level, options, correct_option) VALUES
('Welches Wort passt? "Er hat das Projekt erfolgreich ___."', 'B2', '["abgeschlossen", "angefangen", "verloren", "vergessen"]', 'abgeschlossen'),
('Wählen Sie die richtige Präposition: "Das Buch wurde ___ Englisch übersetzt."', 'B2', '["ins", "aus", "bei", "nach"]', 'ins'),
('Was bedeutet "herausfordernd" auf Englisch?', 'B2', '["challenging", "boring", "simple", "easy"]', 'challenging'),
('Was ist die korrekte Übersetzung von "decision-making process"?', 'B2', '["Entscheidungsprozess", "Arbeitsprozess", "Denkprozess", "Schulprozess"]', 'Entscheidungsprozess'),
('Wählen Sie die richtige Form: "Die Arbeit muss bis morgen ___ sein."', 'B2', '["fertiggestellt", "laufen", "gehört", "vergessen"]', 'fertiggestellt'),
('Wie sagt man "research" auf Deutsch?', 'B2', '["Forschung", "Arbeit", "Urlaub", "Sport"]', 'Forschung'),
('Welches Adjektiv passt? "Das Wetter war ___ angenehm."', 'B2', '["besonders", "häufig", "leicht", "schwer"]', 'besonders'),
('Wählen Sie das passende Synonym für "komplex".', 'B2', '["kompliziert", "einfach", "normal", "leicht"]', 'kompliziert'),
('Wie nennt man den Prozess der Problemanalyse?', 'B2', '["Problemlösung", "Problembildung", "Lösungssuche", "Analyseverlust"]', 'Problemlösung'),
('Was ist die richtige Übersetzung für "long-term goals"?', 'B2', '["langfristige Ziele", "kurze Ziele", "tägliche Aufgaben", "kleine Ziele"]', 'langfristige Ziele');

INSERT INTO question (question_text, level, options, correct_option) VALUES
('How do you say "sustainable development" in German?', 'C1', '["nachhaltige Entwicklung", "entwickelte Nachhaltigkeit", "dauerhafte Entwicklung", "stabile Entwicklung"]', 'nachhaltige Entwicklung'),
('Translate "This topic is highly controversial." to German.', 'C1', '["Dieses Thema ist sehr umstritten", "Dieses Thema ist kontrovers", "Es gibt viele Diskussionen", "Das Thema steht offen"]', 'Dieses Thema ist sehr umstritten'),
('What is the correct form for "Wir ___ das Problem schnell lösen können."', 'C1', '["könnten", "konnten", "möchten", "werden"]', 'könnten'),
('Choose the correct word for "complicated" in German.', 'C1', '["kompliziert", "leicht", "langsam", "erledigt"]', 'kompliziert'),
('Translate "The presentation was impressive." to German.', 'C1', '["Die Präsentation war beeindruckend", "Die Vorstellung war schön", "Es war eine einfache Präsentation", "Die Präsentation war da"]', 'Die Präsentation war beeindruckend'),
('How do you say "to emphasize" in German?', 'C1', '["betonen", "vergleichen", "weglassen", "erklären"]', 'betonen'),
('Translate "The economic implications are complex." to German.', 'C1', '["Die wirtschaftlichen Implikationen sind komplex", "Wirtschaftliche Effekte sind simpel", "Das Wirtschaftliche ist leicht", "Die ökonomische Bedeutung"]', 'Die wirtschaftlichen Implikationen sind komplex'),
('Choose the correct synonym for "efficient" in German.', 'C1', '["effizient", "träge", "unnötig", "langsam"]', 'effizient'),
('How do you say "to negotiate terms" in German?', 'C1', '["Bedingungen verhandeln", "Bedingungen kaufen", "Bedingungen verkaufen", "Bedingungen ignorieren"]', 'Bedingungen verhandeln'),
('What is "responsibility" in German?', 'C1', '["Verantwortung", "Unachtsamkeit", "Erschöpfung", "Freude"]', 'Verantwortung'),
('Translate "The decision was justified." to German.', 'C1', '["Die Entscheidung war gerechtfertigt", "Die Entscheidung war einfach", "Die Entscheidung war überflüssig", "Die Entscheidung war weg"]', 'Die Entscheidung war gerechtfertigt'),
('How do you say "to implement a strategy" in German?', 'C1', '["eine Strategie umsetzen", "eine Strategie löschen", "eine Strategie verstehen", "eine Strategie verlassen"]', 'eine Strategie umsetzen'),
('Choose the correct form for "Er ___ seinen Standpunkt klar."', 'C1', '["erklärte", "erklärt", "erklärten", "erklären"]', 'erklärte'),
('Translate "She is capable of leading the team." to German.', 'C1', '["Sie ist in der Lage, das Team zu führen", "Sie kann nicht führen", "Das Team leitet sie", "Sie ist für das Team da"]', 'Sie ist in der Lage, das Team zu führen'),
('What is "evaluation" in German?', 'C1', '["Bewertung", "Vernachlässigung", "Verhandlung", "Zerstörung"]', 'Bewertung'),
('How do you say "to prioritize tasks" in German?', 'C1', '["Aufgaben priorisieren", "Aufgaben vermeiden", "Aufgaben verzögern", "Aufgaben fallen"]', 'Aufgaben priorisieren'),
('Translate "His argument was convincing." to German.', 'C1', '["Sein Argument war überzeugend", "Sein Argument war leise", "Sein Argument war unsicher", "Es gab kein Argument"]', 'Sein Argument war überzeugend'),
('What is "obstacle" in German?', 'C1', '["Hindernis", "Erfolg", "Ziel", "Strategie"]', 'Hindernis'),
('How do you say "to address an issue" in German?', 'C1', '["ein Problem ansprechen", "ein Problem verstecken", "ein Problem ignorieren", "ein Problem auslassen"]', 'ein Problem ansprechen'),
('Translate "The project needs more resources." to German.', 'C1', '["Das Projekt braucht mehr Ressourcen", "Das Projekt hat Ressourcen", "Das Projekt ist fertig", "Mehr Projekte sind notwendig"]', 'Das Projekt braucht mehr Ressourcen'),
('Choose the correct translation for "ambition".', 'C1', '["Ambition", "Langsamkeit", "Zufriedenheit", "Gegenteil"]', 'Ambition'),
('How do you say "reliable" in German?', 'C1', '["zuverlässig", "unsicher", "langsam", "eilig"]', 'zuverlässig'),
('What is "feedback" in German?', 'C1', '["Rückmeldung", "Schaden", "Reaktion", "Abstand"]', 'Rückmeldung'),
('Translate "We have a strict deadline." to German.', 'C1', '["Wir haben eine strenge Frist", "Es gibt keine Frist", "Wir brauchen keine Frist", "Die Frist ist locker"]', 'Wir haben eine strenge Frist'),
('How do you say "to delegate responsibilities" in German?', 'C1', '["Verantwortungen delegieren", "Verantwortungen verweigern", "Verantwortungen sammeln", "Verantwortungen entfernen"]', 'Verantwortungen delegieren');
INSERT INTO question (question_text, level, options, correct_option) VALUES
('Wählen Sie das richtige Wort: "Das Projekt wurde ___ durchgeführt."', 'C1', '["gründlich", "schnell", "oberflächlich", "einfach"]', 'gründlich'),
('Was bedeutet "Ambivalenz" auf Englisch?', 'C1', '["Ambivalence", "Certainty", "Confusion", "Simplicity"]', 'Ambivalence'),
('Wie sagt man "scientific approach" auf Deutsch?', 'C1', '["wissenschaftlicher Ansatz", "technischer Plan", "soziale Forschung", "unlogische Methode"]', 'wissenschaftlicher Ansatz'),
('Welches Adjektiv passt? "Sein Verhalten war ___ unberechenbar."', 'C1', '["völlig", "teilweise", "immer", "leicht"]', 'völlig'),
('Was bedeutet "strukturiert" auf Englisch?', 'C1', '["structured", "broken", "normal", "chaotic"]', 'structured'),
('Wählen Sie das richtige Synonym für "effektiv".', 'C1', '["wirksam", "langsam", "teuer", "sicher"]', 'wirksam'),
('Welches Wort passt? "Die ___ von Daten ist entscheidend."', 'C1', '["Analyse", "Sorge", "Abneigung", "Reduktion"]', 'Analyse'),
('Was bedeutet "interdisziplinär" auf Englisch?', 'C1', '["interdisciplinary", "basic", "complex", "immediate"]', 'interdisciplinary'),
('Wie sagt man "sophisticated" auf Deutsch?', 'C1', '["raffiniert", "einfach", "grob", "offen"]', 'raffiniert'),
('Wählen Sie die korrekte Übersetzung für "abstract thinking".', 'C1', '["abstraktes Denken", "schnelles Denken", "oberflächliches Denken", "gedankliche Freiheit"]', 'abstraktes Denken');

INSERT INTO question (question_text, level, options, correct_option) VALUES
('Translate "The philosophical implications are profound." to German.', 'C2', '["Die philosophischen Implikationen sind tiefgreifend", "Philosophie ist leicht", "Die Bedeutung ist gering", "Es gibt keine Bedeutung"]', 'Die philosophischen Implikationen sind tiefgreifend'),
('How do you say "to refute an argument" in German?', 'C2', '["ein Argument widerlegen", "ein Argument schaffen", "ein Argument bestätigen", "ein Argument übersehen"]', 'ein Argument widerlegen'),
('What is the correct form for "Hätte er das ___, wäre es anders gewesen."', 'C2', '["gewusst", "wissen", "weiß", "gewisse"]', 'gewusst'),
('Translate "The legal framework has evolved." to German.', 'C2', '["Das rechtliche Rahmenwerk hat sich entwickelt", "Das Rahmenwerk ist alt", "Der Rahmen ist weg", "Es gibt keine Entwicklung"]', 'Das rechtliche Rahmenwerk hat sich entwickelt'),
('Choose the correct word for "meticulous" in German.', 'C2', '["akribisch", "schnell", "leicht", "einfach"]', 'akribisch'),
('How do you say "cultural heritage" in German?', 'C2', '["kulturelles Erbe", "kulturelle Gegenwart", "historisches Erbe", "kulturelle Struktur"]', 'kulturelles Erbe'),
('Translate "He articulated his thoughts clearly." to German.', 'C2', '["Er artikulierte seine Gedanken klar", "Seine Gedanken waren leise", "Er artikulierte nichts", "Er sprach unklar"]', 'Er artikulierte seine Gedanken klar'),
('What is "transparency" in German?', 'C2', '["Transparenz", "Versteck", "Unklarheit", "Verdeckung"]', 'Transparenz'),
('How do you say "to scrutinize details" in German?', 'C2', '["Details hinterfragen", "Details ignorieren", "Details vereinfachen", "Details löschen"]', 'Details hinterfragen'),
('Translate "The discourse was comprehensive." to German.', 'C2', '["Die Diskussion war umfassend", "Es gab keine Diskussion", "Die Diskussion war schlecht", "Es war leicht"]', 'Die Diskussion war umfassend'),
('What is the German word for "intricate"?', 'C2', '["komplex", "einfach", "direkt", "offen"]', 'komplex'),
('Choose the correct synonym for "profound" in German.', 'C2', '["tiefgründig", "flach", "oberflächlich", "einfach"]', 'tiefgründig'),
('How do you say "to challenge assumptions" in German?', 'C2', '["Annahmen infrage stellen", "Annahmen folgen", "Annahmen ignorieren", "Annahmen unterstützen"]', 'Annahmen infrage stellen'),
('Translate "Her analysis was thorough." to German.', 'C2', '["Ihre Analyse war gründlich", "Sie analysierte nicht", "Es war flach", "Ihre Analyse war leicht"]', 'Ihre Analyse war gründlich'),
('What is "equilibrium" in German?', 'C2', '["Gleichgewicht", "Ungleichgewicht", "Ruhe", "Sicherheit"]', 'Gleichgewicht'),
('How do you say "paradigm shift" in German?', 'C2', '["Paradigmenwechsel", "Verschiebung", "Stilwechsel", "Modelländerung"]', 'Paradigmenwechsel'),
('Translate "The theory is widely recognized." to German.', 'C2', '["Die Theorie ist weit anerkannt", "Die Theorie ist neu", "Es gibt keine Theorie", "Die Theorie ist unbekannt"]', 'Die Theorie ist weit anerkannt'),
('What is "ethical dilemma" in German?', 'C2', '["ethisches Dilemma", "ethische Freiheit", "ethische Vereinfachung", "dilemmalose Ethik"]', 'ethisches Dilemma'),
('Choose the correct form for "Sie ___ die Argumente sorgfältig analysiert."', 'C2', '["hat", "hätte", "haben", "wird"]', 'hat'),
('Translate "The data supports the hypothesis." to German.', 'C2', '["Die Daten stützen die Hypothese", "Die Daten ignorieren die Hypothese", "Daten sind weg", "Es gibt keine Daten"]', 'Die Daten stützen die Hypothese'),
('How do you say "conceptual clarity" in German?', 'C2', '["konzeptionelle Klarheit", "unklare Konzepte", "einfache Konzepte", "direkte Klarheit"]', 'konzeptionelle Klarheit'),
('What is "sophisticated analysis" in German?', 'C2', '["raffinierte Analyse", "einfache Analyse", "schnelle Analyse", "falsche Analyse"]', 'raffinierte Analyse'),
('Translate "The nuances of language." to German.', 'C2', '["Die Nuancen der Sprache", "Die Sprache ist klar", "Keine Nuancen", "Einfache Worte"]', 'Die Nuancen der Sprache'),
('How do you say "intellectual property" in German?', 'C2', '["geistiges Eigentum", "materielles Eigentum", "normales Eigentum", "falsches Eigentum"]', 'geistiges Eigentum'),
('What is "strategic alignment" in German?', 'C2', '["strategische Ausrichtung", "strategischer Wandel", "einfacher Plan", "unstrategische Struktur"]', 'strategische Ausrichtung');
INSERT INTO question (question_text, level, options, correct_option) VALUES
('Was bedeutet "konzeptionell" auf Englisch?', 'C2', '["conceptual", "confused", "historical", "pragmatic"]', 'conceptual'),
('Wählen Sie das passende Adjektiv: "Die Situation war ___ angespannt."', 'C2', '["hochgradig", "normal", "leicht", "immer"]', 'hochgradig'),
('Wie sagt man "linguistic nuances" auf Deutsch?', 'C2', '["sprachliche Nuancen", "einfache Sprache", "Sprechstörungen", "Wortverlust"]', 'sprachliche Nuancen'),
('Was bedeutet "synthetisieren" auf Englisch?', 'C2', '["synthesize", "analyze", "ignore", "break"]', 'synthesize'),
('Wählen Sie die richtige Präposition: "Er hat sich ___ dem Thema intensiv beschäftigt."', 'C2', '["mit", "bei", "durch", "über"]', 'mit'),
('Was ist die korrekte Übersetzung für "nuanced perspective"?', 'C2', '["nuancierte Perspektive", "flache Perspektive", "direkte Perspektive", "einfache Sicht"]', 'nuancierte Perspektive'),
('Wie sagt man "intellectual challenge" auf Deutsch?', 'C2', '["intellektuelle Herausforderung", "körperliche Aufgabe", "sozialer Druck", "mentale Flucht"]', 'intellektuelle Herausforderung'),
('Welches Wort passt? "Das Argument war ___ überzeugend."', 'C2', '["äußerst", "mäßig", "gering", "leicht"]', 'äußerst'),
('Was bedeutet "pragmatisch" auf Englisch?', 'C2', '["pragmatic", "complex", "chaotic", "simple"]', 'pragmatic'),
('Wählen Sie das passende Substantiv: "Die ___ der Analyse war beeindruckend."', 'C2', '["Tiefe", "Oberfläche", "Schlichtheit", "Langsamkeit"]', 'Tiefe');
